### ISSUE TITLE
NYC Block Explorer

### ISSUE THREAD

**Issue by nicovs** [NewYorkCoin-NYC/ToDo#10]
Like: https://altminer.net/explorer/NYC

But also with Wallet address status

**Comment by jamesburrell2** [comment]
Nicovs - we had an Insight blockexplorer (https://insight.is/)  at http://45.79.186.226 but it doesn't connect anymore

**Comment by nicovs** [comment]
ok, trying to pick this up myself :)

**Comment by jamesburrell2** [comment]
Any progress?

**Comment by ltanyc** [comment]
done https://explorer.nycoin.community/
