### ISSUE TITLE
Improve QT wallet

### ISSUE THREAD

**Issue by drarko** [NewYorkCoin-NYC/ToDo#3]

**Comment by MrSlosh** [comment]
I will have a look at this.

**Comment by MrSlosh** [comment]
Just to keep this updated, wallet version 1.1.2.2 is out which includes and update to openssl 1.0.2n.
Version 1.2 is in the works which will bring the codebase up to the 2015 TronRex takeover point and beyond. The test suite is currently being updated and as soon as that is clear then we can start testing the wallet and daemon on the community at large.

**Comment by ltanyc** [comment]
new wallet is out see https://github.com/NewYorkCoin-NYC/nycoin/releases
