### ISSUE TITLE
Technical roadmap

### ISSUE THREAD

**Issue by drarko** [NewYorkCoin-NYC/ToDo#6]

**Comment by cmelion** [comment]
The technical roadmap should start with:
1) Removing legacy bitcoin alert system (causes issues with QT wallet and is deprecated anyway)
2) Improve resistance to 51% attack.
3) Introduce Segwit
4) Add support for Lightning Network (LN)
5) Add support for smart contracts (MAST/“Merklized Script”)
6) Introduce smart contract powered burn initiatives (lotteries, etc.)

**Comment by cmelion** [comment]
Once roadmap is agreed upon, communicating it to the public in an appealing manner is key.
Maybe something like this?
https://www.campuscoinproject.org/roadmap/

**Comment by cmelion** [comment]
Halving schedule to be introduced in a time delayed fashion with other major improvements to incentivize nodes to upgrade with sufficient lead time to reduce the chance of a chain split:

.5 years  --> 5000
1 year      --> 2500
1.5 years --> 1250
2 years   --> 625
2.5 years --> 312
3 years     --> 156

**Comment by cmelion** [comment]
Coin burn vehicles:
- Smart contract powered lotteries (requires MAST or RSK like capabilities)
- Coin swaps that require proof of burn (see  Counterparty and its clone, Dogeparty https://counterparty.io/)
- Community sponsored wallets, mining tools, pool software that takes some portion of transactions and sends it to the burn address.

**Comment by cmelion** [comment]
As far as the Dogeparty/Counterparty concept, I toyed with the idea of creating a coin for each burrough each with unique properties.
This is where we could address some of the suggestions from the community, regarding IOTA like behavior, GPU mining, Proof of Stake or mining algorithms that solve real world problems for example, without creating hard forks or conflict.

**Comment by cmelion** [comment]
Forensic extensions to the block explorer for trend analysis, identifying how much NYC is likely out of circulation due to lost keys, etc.

**Comment by Newyorkcoinholder** [comment]
I think that a big problem for the evolution of nyc is that people don't know how much nycoin in circulation because of loss passphras, hard disk in garbage..   a redeem like paccoin is doing will permit  to know how many coins still in circulation because pac holder must send their coins to an official pac adress and then they send back the new coin to the new wallet adress. 
People which don't send old coin will never receive new coin and the problem will be solved. We could divide the max supply by 1000 or 100 to up the price? So.. fork nyc to nyc cash   ?

**Comment by NewYorkCoinFan** [comment]
These are some great ideas Cmelion, but it would be useful to try and see this problem from a different angle. What we are basically trying to accomplish is a reward system for miners to keep the network sustainable, if I am right? Here are my suggestions:

This idea might seem strange, however, it's whole different view in which we can create a merchandise brand around NYC and generate money to buy mining gear and pay the electricity without a reward system in place. Another option would be to fund this process by organizing a monthly NYC lottery or the ability to bet with NYC. 

This idea could (partly) replace the reward system if executed correctly. Especially as a marketer, I could see this work. Even though, it's definitely not the easiest way out.

**Comment by Newyorkcoinholder** [comment]
Why not change from POW to POS ?

**Comment by cmelion** [comment]
@Newyorkcoinholder I understand the concern about not knowing how much is in circulation.  Before making significant changes we should ask questions and come up with thoughtful answers (please edit this post with additional questions and answers):
1) Will people suddenly stop losing keys?
2) What if a person stores a large number of NYC on a usb stick and forgets about it for 10 years, do they forfeit their NYC?

**Comment by cmelion** [comment]
Newyorkcoinholder POS is worthy of consideration.  I understand how it works in theory, it would be nice to elaborate on some real world success stories for POS.

**Comment by cmelion** [comment]
@NewYorkCoinFan I have some concerns that your plan would lead centralization.

**Comment by Newyorkcoinholder** [comment]
@cmelion  . First we have to determinate which way to follow together before any evolution of nyc. We need an action plan that all the community will follow.
Your 2 questions are interesting and all the community should give his opinion.

**Comment by ltanyc** [comment]
done https://nycoin.community/roadmap.html
