### ISSUE TITLE
Web wallet

### ISSUE THREAD

**Issue by drarko** [NewYorkCoin-NYC/ToDo#8]

**Comment by cmelion** [comment]
Should I create a new Issue or use this one?

I'm working on a simple webwallet using TREZOR as a private key storage 
There is enough example code and documentation for Trezor, I'm not so sure about Ledger yet.

https://github.com/trezor/webwallet

**Comment by jamesburrell2** [comment]
Maybe keep it in this issue because I think your version will be more secure than other web wallets. And I agree re: the USB stick, which gives new users a low barrier of entry yet some security comfort.

**Comment by jamesburrell2** [comment]
What about this webwallet? https://github.com/johnathanmartin/piWallet/wiki/Installation

**Comment by Newyorkcoinholder** [comment]
I use ledger nano as hard wallet for several coins and tokens and it's really secure. It will be great if it was possible to add NYC in a hard wallet but your idea of a more secure web wallet is good

**Comment by NYCoinNova** [comment]
If  we have the block chain backed up and available for download. users would  be able to just carry their wallet.dat file on usd or encrypted usb.  Have access on any computer in minutes with the blockchain synced. 

Just a thought if this is possible...
Is there a way to make the wallet  available on a public node on a VM that you "borrow" to use with your ny coin wallet.dat file so you  dont have to download  the wallet or sync, just back your wallet  up to the node on vm.
Node would be public but connection encrypted. So users would be able to log on to  the community website, register for online wallet and access public  node.  Their wallet.bat file would remain on their phone and they would sync with the network to share the blockchain and QT wallet to avoid download and sync.

**Comment by nicovs** [comment]
Initial web wallet online on https://wallet.nycoin.info.

=> based on piWallet, so no control over private keys.
The service is a best effort on implementing that.

There are better and more secure ways to implement this. For now this will suffice.
