### ISSUE TITLE
Versioning and deployment for the "Official" website

### ISSUE THREAD

**Issue by cmelion** [NewYorkCoin-NYC/ToDo#9]

**Comment by sevenshadow** [comment]
Hi Cmelion,

I have a lot of web dev experiance, and I was wondering if you wanted help with this.

**Comment by cmelion** [comment]
Hi sevenshadow,
I've added you to the Organization.
Are you monitoring the discord channels?

**Comment by sevenshadow** [comment]
Just started to monitor them today.

**Comment by zzbconcept** [comment]
hey, can I join ? I'm zzburatorul from discord

**Comment by jamesburrell2** [comment]
What’s up Alex – I don’t have an issue with you joining.

Best regards,
James S. Burrell,II
jamesburrell2@hotmail.com<mailto:jamesburrell2@hotmail.com>
Twitter: @jamesburrell2

NOTICE: This email message is for the sole use of the intended recipient(s) and may contain information that is confidential and protected from disclosure by the attorney-client privilege, as attorney work product, or by other applicable privileges. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

**Comment by cmelion** [comment]
What is your github ID?

**Comment by drarko** [comment]
@zzbconcept added

**Comment by Santana810** [comment]
Please add the address to both gyms in NYC or add link to address website.

**Comment by ltanyc** [comment]
this issue can probably be closed, but before that can you add me to org as well? ;)
